---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.repo_name }}
  namespace: "{{ .Values.repo_name }}-{{ .Values.environment }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.repo_name }}-{{ .Values.environment }}"
      environment: {{ .Values.environment }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.repo_name }}-{{ .Values.environment }}"
        environment: {{ .Values.environment }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          name: "{{ .Values.repo_name }}-{{ .Values.environment }}"
          ports:
            - containerPort: {{ .Values.target_port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health_path }}
              port: {{ .Values.target_port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1