---
version: 0.2
batch:
  build-list:
    - identifier: build1
      env:
        parameter-store:
          KUBE_CONFIG: "$KUBECONFIG_NAME"
          DOCKER_PASSWORD: "$DOCKER_PASSWORD_PS"
          DOCKER_USER: "$DOCKER_USER_PS"
          DOCKER_REPO: "$DOCKER_REPO_PS"
      ignore-failure: true
    - identifier: build2
      env:
        variables:
          HELM_CHART: ""
          HELM_CHART_VERSION: ""
          REPO_NAME: ""
          IMAGE_REPO_NAME: ""
          AWS_ACCOUNT_ID: ""
          AWS_CLUSTER_REGION: ""
          EKS_ROLE_ARN: ""
          CLUSTER_NAME: ""
          ENVIRONMENT: ""
          REPLICAS: ""
          APP_FQDN: ""
env:
  variables:
    HELM_CHART: ""
    HELM_CHART_VERSION: ""

phases:
  install:
    commands:
      - apt-get update
#      - env
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm version --short
      - helm plugin install https://github.com/hypnoglow/helm-s3.git
      - apt-get -y install jq python3-pip python3-dev gettext-base && pip3 install --upgrade awscli
      - curl -s -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl
      - curl -s -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl.sha256
      - sha256sum -c kubectl.sha256
      - chmod +x ./kubectl
  build:
    commands:
      - ./scripts/kubernetes/k8s.sh




