version: 0.2
env:
  parameter-store:
    RP_API_KEY: "$RP_TOKEN_NAME"
  variables:
    SELENIUM_SERVER_URL: http://127.0.0.1:4444/wd/hub
    PASS_RATE: 100
    APP_TARGET_URL: ""

phases:
  install:
    commands:
      - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name selenium selenium/standalone-firefox:3.141.59 -l "error"
      - pip install pytest pytest-reportportal reportportal-client selenium unittest-xml-reporting junitparser -qq
  build:
    commands:
      - python3 -m pytest --junitxml=report.xml ./scripts/selenium_tests/selenium_tests.py --reportportal --tb=no
      - python3 ./scripts/selenium_tests/selenium_status_check.py --report ./report.xml --pass-rate "${PASS_RATE}"

reports:
  Selenium:
    file-format: JunitXml
    files:
      - ./report.xml
